# Generated by Django 4.0.1 on 2022-01-19 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='despesas',
            new_name='Despesa',
        ),
        migrations.RenameModel(
            old_name='receitas',
            new_name='Receita',
        ),
    ]
