# Generated by Django 4.0.1 on 2022-01-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restAPI', '0002_rename_despesas_despesa_rename_receitas_receita'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesa',
            name='categoria',
            field=models.CharField(choices=[('ALIMENTACAO', 'Alimentação'), ('SAUDE', 'Saúde'), ('MORADIA', 'Moradia'), ('TRANSPORTE', 'Transporte'), ('EDUCACAO', 'Educação'), ('LAZER', 'Lazer'), ('IMPREVISTOS', 'Imprevistos'), ('OUTRAS', 'Outras')], default='OUTRAS', max_length=15),
        ),
    ]
